name: Docker

on:
  # Allow manual workflow triggering from the "Actions" tab.
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Container variant to build
        options:
          - rust-1.69.0-alsa

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}_${{ github.event.inputs.variant }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx.
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.event.inputs.variant }}
          push: true
          tags: ${{ github.event.inputs.variant }}
