name: Docker

on:
  # Allow manual workflow triggering from the "Actions" tab.
  workflow_dispatch:
    inputs:
      variant:
        type: choice
        description: Container variant to build
        options:
          - rust-1.69.0-alsa
          - rust-1.73.0-alsa
          - rust-1.80.0-alsa
          - rust-1.81.0-alsa
          - rust-1.85.0-alsa
          - rust-1.86.0-alsa

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}_${{ github.event.inputs.variant }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/login-action
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx.
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.event.inputs.variant }}
          push: true
          tags: ghcr.io/${{ github.repository}}:${{ github.event.inputs.variant }}
